name: build-production
on:
  push:
    tags:
      - '*'
jobs:
  build-zip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout all repositories
      uses: actions/checkout@v2

    - name: Cache for node_modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        check-latest: true

    - name: Yarn create everything
      run: |
        yarn install
        yarn zip

    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.DEPLOY_TOKEN }}
        artifact: './futureshop.zip'
