name: build-production
on: [push]
jobs:
  build-zip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout all repositories
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        check-latest: true

    - name: Yarn create everything
      run: |
        yarn install
        yarn zip

    - name: Create Release
      id: create_release
      uses: actions/release-action
      with:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        artifact: './futureshop.zip'
